# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.1.0
  ruby: circleci/ruby@2.1.2

jobs:
  install_python:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - "ls /tmp/cci_pycache"
      - persist_to_workspace:
          root: workspace
          paths:
            - /tmp/cci_pycache
  test:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/**/*_spec.rb

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-workflow:
    jobs:
      - install_python
      - test:
          requires:
            - install_python
